version: '3'
services:
#mssql docker
  ridewithme-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password_123!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - ridewithmenet

  rabbitmq:
    image: rabbitmq:3.12.1-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
    networks:
      - ridewithmenet

  ridewithme-rabbitmq:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.mailer
    environment:
      - RABBITMQ_HOST=localhost
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
    depends_on:
      - rabbitmq
      - ridewithme-sql
      - ridewithme-api
    networks:
      - ridewithmenet
    ports:
      - 7111:80

  ridewithme-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:ridewithme=Server=ridewithme-sql,1433;Database=ridewithme_2024;User=sa;Password=Password_123!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5284:5284
    networks:
      - ridewithmenet
    links:
      - ridewithme-sql
    depends_on:
      - ridewithme-sql
    
      
networks:
  ridewithmenet:
    driver: bridge      